#!/usr/bin/env python

from datetime import datetime
from itertools import dropwhile
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Union

import attr
import pandas as pd
import polars as pl

################################################################################
# Set Up
################################################################################
# Grab the location of various things from the config
input_dict: Path   = dict(config["inputs"])
output_dir: Path   = Path(config["output_dir"])
gtf_file: Path     = Path(config['gtf_file'])

@attr.s(frozen=True, auto_attribs=True, kw_only=True)
class Input:
    """Represents all necessary meta data"""
    gwas: str
    fusion: List[str]
    predixscan: List[str]
    ancestries: List[str]

# Set up data-structure
inputs: Dict[str, Input] = dict()
for key in input_dict:
    f_names=[name for name in input_dict[key].keys() if 'fusion' in name]
    f = [input_dict[key][name] for name in f_names]
    p_names=[name for name in input_dict[key].keys() if 'predixscan' in name]
    p = [input_dict[key][name] for name in p_names]
    g=input_dict[key]['gwas']
    ancestries = [n.split('_')[1] for n in f_names]

    inputs[key] = Input(gwas = g, fusion = f, predixscan = p, ancestries = ancestries)


print(inputs)

################################################################################
# Directives
################################################################################
onerror:
    """Code that gets called  if / when the snakemake pipeline exits with an error.
    The `log` variable contains a path to the snakemake log file which can be parsed
    for more information. Summarizes information on failed jobs and writes it to the
    output.
    """
    try:
        path = Path(log)
        RULE_PREFIX = "Error in rule "
        LOG_PREFIX = "    log: "
        CMD_PREFIX = "Command "

        with path.open("r") as fh:
            lines: Iterable[str] = fh.readlines()

        while lines:
            lines = list(dropwhile(lambda l: not l.startswith(RULE_PREFIX), lines))
            if lines:
                rule_name = lines[0].rstrip()[len(RULE_PREFIX) : -1]
                lines = dropwhile(lambda l: not l.startswith(LOG_PREFIX), lines)
                log_path = Path(next(lines).rstrip()[len(LOG_PREFIX) :].split()[0])

                print(f"========== Start of Error Info for {rule_name} ==========")
                print(f"Failed rule: {rule_name}")
                print(f"Contents of log file: {log_path}")
                with log_path.open("r") as fh:
                    for line in fh.readlines():
                        print(f"    {line.rstrip()}")
                print(f"=========== End of Error Info for {rule_name} ===========")
    except Exception as ex:
        print("################################################")
        print("Exception raised in snakemake onerror handler.")
        print(str(ex))
        print("################################################")


################################################################################
# Beginning of rule declarations
################################################################################
rule all:
    """
    Default rule that is executed when snakemake runs.  The 'inputs' here list the set of files
    that the pipeline will generate by default if a specific list isn't provided.
    """
    input:
        [f'{output_dir}/combined_results/{key}.tsv' for key, value in inputs.items()]
        
rule clean_predixscan:
    input:
        gwas = lambda wc: inputs[wc.key].gwas,
        gtf = gtf_file
    params:
        fusion = lambda wc: inputs[wc.key].fusion,
        predixscan = lambda wc: inputs[wc.key].predixscan,
        ancestries = lambda wc: inputs[wc.key].ancestries,
    output:
        '{output_dir}/combined_results/{key}.tsv'
    log:
        '{output_dir}/combined_results/{key}.log'
    shell:
        "python modules/main.py " 
        "--gwas {input.gwas} "
        "--ancestries {params.ancestries} "
        "--fusions {params.fusion} "
        "--gtf {input.gtf} "
        "--predixscans {params.predixscan} "
        "--output {output}"