input_dir: '~/input_dirctory'
output_dir: '~/output_results'
gtf: '~/path_to_ensembl_gtf'
input_suffix: '_summstats.gz'
gtex_file: 'WEIGHTS/GTExv8.ALL.Thyroid.nofilter.pos'
gtex_weight_dir: 'WEIGHTS/'
ref_ld_chr: '~/LDREF/1000G.EUR.'
ancestry: 'mixed'
fusion_script: 'FUSION.assoc_test.R'
