map_file: "example_inputs/map.txt"
gnomad_ref_dir: "example_inputs/gnomAD/ref"
gnomad_flag_dir: "example_inputs/gnomAD/flagged"
output_tsv: "example_output/aligned"
output_plots: "example_output/plots"